CREATE OR REPLACE TRIGGER STAR.NSPCDI_BI_CR BEFORE INSERT
ON STAR.NS_PIECE_DISPOSITIONS REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
BEGIN
  :NEW.CREATED_BY := USER;
  :NEW.DATE_CREATED := CURRENT_TIMESTAMP;
  :NEW.REC_STATUS := 'A';
  :NEW.NS_PIECE_DISP_ID := NSPCDI_ID_SEQ.NEXTVAL;
  IF :NEW.EDITION IS NULL THEN 
    :NEW.EDITION := 1;
  END IF;
END;
/