DROP VIEW STAR.NS_PIECE_DISPOSITIONS_VW;

/* Formatted on 11/4/2020 3:29:20 PM (QP5 v5.185.11230.41888) */
CREATE OR REPLACE VIEW STAR.NS_PIECE_DISPOSITIONS_VW
(
   NS_SITE,
   NS_ID,
   NS_STATUS,
   NS_NOTIFIED_BY,
   NS_STAGE,
   NS_RESOLUTION_TEXT,
   NS_AREA,
   NS_CIRC,
   NS_CODE,
   NS_DATE,
   NS_DESC,
   NS_EQUIP,
   NS_PROB_OWNER,
   NS_PROD,
   NS_REASON,
   NS_REF,
   NS_ROOT_CAUSE,
   NS_RES_STATUS,
   NS_ALLOY,
   NS_HEAT,
   NS_COM,
   NS_INSP_ACTION,
   NS_OUTCOME,
   NS_PO,
   NS_REM_ACTION,
   NS_LINE,
   NS_PIECE_IDENTITIES,
   NS_BATCH_DISPOSITION,
   NS_COUNT_AFFECTED,
   NS_WEIGHT_AFFECTED,
   NS_WT_UOM,
   NS_PART_CODE,
   NS_YIELD_LOSS,
   NS_NOT_FIT_FOR_PURPOSE_WT,
   NS_TOTAL_COST,
   NS_CURRENCY,
   NS_DELAY,
   NS_REASON_DESC,
   NS_PRODUCT_DESC,
   NS_CODE_DESC,
   NS_PROCESS,
   NS_AREA_DESC,
   NS_EQUIP_TYPE,
   NS_EQUIP_DESC,
   NS_PIECE_ID,
   NS_PIECE_COUNT,
   NS_PIECE_WEIGHT,
   NS_PIECE_WT_UOM,
   NS_PIECE_DISP_REASON,
   NS_PIECE_DISPOSITION,
   NS_PIECE_COMMENTS
)
AS
   SELECT NEH.SITE NS_SITE,
          NEH.NS_EVENT_ID NS_ID,
          NEH.STATUS NS_STATUS,
          NEH.NOTIFIED_BY NS_NOTIFIED_BY,
          NEH.AREA_CODE NS_STAGE,
          NEH.RESOLUTION_TEXT NS_RESOLUTION_TEXT,
          NC.NS_GROUP_CODE NS_AREA,
          SR.ROLE_TITLE NS_CIRC,
          NEH.NS_CODE NS_CODE,
          NEH.DATE_OCCURRED NS_DATE,
          NEH.EVENT_DESC NS_DESC,
          NEH.EQUIPMENT_CODE NS_EQUIP,
          NEH.PROBLEM_OWNER NS_PROB_OWNER,
          NEH.PRODUCT_CODE NS_PROD,
          NRC.REASON_CODE NS_REASON,
          NEH.NSN_REF NS_REF,
          NEH.ROOT_CAUSE NS_ROOT_CAUSE,
          NEH.RESOLUTION_STATUS NS_RES_STATUS,
          NEL.ALLOY_CODE NS_ALLOY,
          NEL.CAST_NUMBER NS_HEAT,
          NEL.COMMENTS NS_COM,
          NEL.INSPECTION_ACTION NS_INSP_ACTION,
          NEL.REMEDIAL_OUTCOME NS_OUTCOME,
          NEL.PROCESS_ORDER NS_PO,
          NEL.REMEDIAL_ACTION NS_REM_ACTION,
          NEL.LINE_NUMBER NS_LINE,
          NBD.PIECE_ID NS_PIECE_IDENTITIES,
          NDC.DISPOSITION_DESC NS_BATCH_DISPOSITION,
          NBD.PIECE_COUNT NS_COUNT_AFFECTED,
          NBD.PIECE_WEIGHT NS_WEIGHT_AFFECTED,
          NBD.WT_UOM NS_W_UOM,
          TPC.PART_CODE NS_PART_CODE,
          NEL.YIELD_LOSS NS_YIELD_LOSS,
          NEL.NOT_FIT_FOR_PURPOSE NS_NOT_FIT_FOR_PURPOSE_WT,
          NEL.TOTAL_COST NS_TOTAL_COST,
          NEL.CURRENCY_CODE NS_CURRENCY,
          NEL.DELAY NS_DELAY,
          NRC.DESCRIPTION NS_REASON_DESC,
          NSP.PRODUCT_NAME NS_PRODUCT_DESC,
          NC.NS_DESCRIPTION NS_CODE_DESC,
          NC.PROCESS_CODE NS_PROCESS,
          NGC.NS_GROUP_DESCRIPTION NS_AREA_DESC,
          NEQ.EQUIPMENT_TYPE NS_EQUIP_TYPE,
          NEQ.EQUIPMENT_DESCRIPTION NS_EQUIP_DESC,
          NPD.PIECE_ID NS_PIECE_ID,
          NPD.PIECE_COUNT NS_PIECE_COUNT,
          NPD.PIECE_WEIGHT NS_PIECE_WEIGHT,
          NPD.WT_UOM NS_PIECE_WT_UOM,
          NPDR.PIECE_REASON NS_PIECE_DISP_REASON,
          NPC.DISPOSITION_DESC NS_PIECE_DISPOSITION,
          NPD.COMMENTS NS_PIECE_COMMENTS
     FROM NS_EVENT_HEADERS NEH,
          NS_EVENT_LINES NEL,
          NS_CODES NC,
          ST_ROLES SR,
          NS_EQUIPMENT NEQ,
          NS_REASON_CODES NRC,
          NS_GROUP_CODES NGC,
          NS_DISPOSITION_CODES NDC,
          NS_DISPOSITION_CODES NPC,
          NS_PIECE_DISPOSITIONS NBD,
          NS_PIECE_DISPOSITIONS NPD,
          NS_PRODUCTS NSP,
          TE_PART_CODES TPC,
          NS_PIECE_DISP_REASONS NPDR
    WHERE     NEH.NS_EVENT_ID = NEL.NS_EVENT_ID
          AND NC.NS_CODE = NEH.NS_CODE
          AND NC.SITE = NEH.SITE
          AND SR.ROLE_ID = NEH.ROLE_ID
          AND NEH.REC_STATUS = 'A'
          AND NEH.EQUIPMENT_CODE = NEQ.EQUIPMENT_CODE
          AND NEQ.REC_STATUS = 'A'
          AND NEQ.SITE = NEH.SITE
          AND NEH.REASON_CODE_ID = NRC.REASON_CODE_ID
          AND NRC.REC_STATUS = 'A'
          AND NGC.NS_GROUP_CODE = NC.NS_GROUP_CODE
          AND NGC.REC_STATUS = 'A'
          AND TPC.PART_CODE_ID(+) = NEL.PART_CODE_ID
          AND TPC.REC_STATUS(+) = 'A'
          AND NBD.NS_EVENT_ID(+) = NEL.NS_EVENT_ID
          AND NBD.LINE_NUMBER(+) = NEL.LINE_NUMBER
          AND NBD.DISPOSITION_TYPE(+) = 'B'
          AND NPD.NS_EVENT_ID(+) = NEL.NS_EVENT_ID
          AND NPD.LINE_NUMBER(+) = NEL.LINE_NUMBER
          AND NPD.DISPOSITION_TYPE(+) = 'P'
          AND NBD.REC_STATUS(+) = 'A'
          AND NPD.REC_STATUS(+) = 'A'
          AND NPDR.DISP_REASON_ID(+) = NPD.DISP_REASON_ID
          AND NPDR.REC_STATUS(+) = 'A'
          AND NDC.DISPOSITION_ID(+) = NBD.DISPOSITION_ID
          AND NPC.DISPOSITION_ID(+) = NPD.DISPOSITION_ID
          --AND NDC.REC_STATUS(+) = 'A' -- STCR 7547
          AND NEH.PRODUCT_CODE = NSP.PRODUCT_CODE
          AND NEH.SITE = NSP.SITE;


DROP PUBLIC SYNONYM NS_PIECE_DISPOSITIONS_VW;

CREATE OR REPLACE PUBLIC SYNONYM NS_PIECE_DISPOSITIONS_VW FOR STAR.NS_PIECE_DISPOSITIONS_VW;


GRANT SELECT ON STAR.NS_PIECE_DISPOSITIONS_VW TO DISCOVERER_SELECT;

GRANT SELECT ON STAR.NS_PIECE_DISPOSITIONS_VW TO EXT_TABLEAU;

GRANT SELECT ON STAR.NS_PIECE_DISPOSITIONS_VW TO EXT_TMT_TABLEAU;

GRANT SELECT ON STAR.NS_PIECE_DISPOSITIONS_VW TO E_TABLEAU;

GRANT SELECT ON STAR.NS_PIECE_DISPOSITIONS_VW TO STAR_DISCOVERER;

GRANT SELECT ON STAR.NS_PIECE_DISPOSITIONS_VW TO STAR_VIEW_ONLY;
